codecov:
  require_ci_to_pass: true

component_management:
  individual_components:
    - component_id: attribute-dsl
      name: "attribute-dsl"
      paths:
        - src/**

coverage:
  precision: 2
  round: down
  range: "75...100"
