[application]
asset_dir = "public"
name = "attribute-dsl"
out_dir = "dist"

[web.app]
base_path = "attribute-dsl"
title = "attribute-dsl | Rust attribute parser helpers"

[web.watcher]
index_on_404 = true
reload_html = true
watch_path = [ "src", "public" ]
